---
name: Context Example

"on":
  push:
    branches:
      - main

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step 1: Action"
        run: |
          echo "Hello! $MY_ACTION"
        env:
          MY_ACTION: ${{ github.action }}
      - name: "My Step 2: Actor"
        run: |
          echo "Hi! $MY_ACTOR"
        env:
          MY_ACTOR: ${{ github.actor }}
